version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ebanking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d   # ✅ exécute les scripts *.sql
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: my_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolith_app
    ports:
      - "8090:8080"
    depends_on:
      - postgres
      - elasticsearch
    restart: always

volumes:
  pgdata:
  esdata:

  
